### ISSUE TITLE
AWS now supports up to 2 subscription filters per log group.

### ISSUE THREAD

**Issue by sejba** [tsub/serverless-plugin-subscription-filter#24]
The plugin hard-codes only one subscription filter per log group. It also has the "stage" property just to handle this.
Is there a chance the plugin could be changed accordingly to the new AWS limits?
Thanks.

**Comment by kennedysam97** [comment]
Should be a 1-line change on line 114 to fix..

**Comment by b-tin** [comment]
Could pls help to review, update to support 2 filter subscription https://github.com/tsub/serverless-plugin-subscription-filter/pull/31

```yaml
...
functions:
  monitoring:
    handler: handler.main
    layers:
      - "${cf:create-lambda-layers-ops.BtinDashpython311DashrequestsLambdaLayerQualifiedArn}"
      - "${cf:create-lambda-layers-ops.BtinDashpython311DashmarshmallowLambdaLayerQualifiedArn}"
    timeout: 60
    tags:
      monitoring: 'true'
    events:
      - subscriptionFilter:
          stage: ops
          logGroupName: /aws/lambda/log-group
          filterPattern: '{ ($.errorCode = "pattern-1") }'
      - subscriptionFilter:
          stage: ops
          logGroupName: /aws/lambda/log-group
          filterPattern: '{ ($.eventName = "pattern-2*") }'
```
