### ISSUE TITLE
The specified log group does not exist.

### ISSUE THREAD

**Issue by nkhine** [tsub/serverless-plugin-subscription-filter#8]
i get this error:

```
$ sls deploy --stage staging --region eu-west-1
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Compiling /aws/lambda/PHPErrors subscription filter object...

  Serverless Error ---------------------------------------

  The specified log group does not exist.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information -----------------------------
     OS:                     linux
     Node Version:           9.11.1
     Serverless Version:     1.30.0
```

serverless.yaml

```
service: php-errors

provider:
  name: aws
  runtime: nodejs8.10
  memorySize: 128
  environment:
    REGION: ${file(./config.js):${opt:stage}.REGION}
    TOKEN: ${file(./config.js):${opt:stage}.TOKEN}
    ROOM: ${file(./config.js):${opt:stage}.ROOM}
  iamRoleStatements:
  - Effect: Allow
    Action:
      - ec2:Describe*
    Resource: '*'
plugins:
  - serverless-offline
  - serverless-plugin-subscription-filter
functions:
  logs:
    handler: index.handler
    events:
      - subscriptionFilter:
          stage: staging
          logGroupName: /aws/lambda/PHPErrors
          filterPattern: '?"PHP Fatal" ?"WordPress database error" ?"PHP Parse error"'
```

what am i missing?
