### ISSUE TITLE
Property error when multiple functions are defined in serverless.yml

### ISSUE THREAD

**Issue by ds0440** [tsub/serverless-plugin-subscription-filter#9]
When multiple functions are defined within serverless.yml this plugin encounters an unhandled property error during deployment. I think this is because I am not defining a subscriptionFilter event for all of my functions.

```
$ sls deploy
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Injecting required Python packages to package...

  Type Error ---------------------------------------------

  Cannot read property 'logGroupName' of undefined

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
```

serverless.yml
```
service: test-service

provider:
  name: aws
  stage: dev

functions:
  function1:
    handler: function1.lambda_handler
    timeout: 30
    runtime: python3.6
    events:
      - subscriptionFilter:
          stage: dev
          logGroupName: /aws/lambda/logGroup
          filterPattern: ERROR
  function2:
    handler: function2.lambda_handler
    timeout: 30
    runtime: python3.6
    events:
      - http:
          method: POST
          path: /
```
